import { Exercise, MuscleCategory } from './types';

export const exercises: Exercise[] = [
  // ==================== PECTORAUX ====================
  { id: 'bench-press', name: 'Développé couché barre', category: 'chest', description: 'Exercice de base pour les pectoraux' },
  { id: 'bench-press-db', name: 'Développé couché haltères', category: 'chest', description: 'Meilleure amplitude de mouvement' },
  { id: 'incline-bench-press', name: 'Développé incliné barre', category: 'chest', description: 'Cible le haut des pectoraux' },
  { id: 'incline-bench-db', name: 'Développé incliné haltères', category: 'chest', description: 'Haut des pectoraux avec haltères' },
  { id: 'decline-bench-press', name: 'Développé décliné barre', category: 'chest', description: 'Cible le bas des pectoraux' },
  { id: 'decline-bench-db', name: 'Développé décliné haltères', category: 'chest', description: 'Bas des pectoraux avec haltères' },
  { id: 'dumbbell-fly', name: 'Écarté couché haltères', category: 'chest', description: 'Isolation des pectoraux' },
  { id: 'incline-fly', name: 'Écarté incliné haltères', category: 'chest', description: 'Isolation haut des pectoraux' },
  { id: 'cable-crossover', name: 'Crossover poulie haute', category: 'chest', description: 'Finition pectoraux' },
  { id: 'cable-crossover-low', name: 'Crossover poulie basse', category: 'chest', description: 'Haut des pectoraux' },
  { id: 'cable-fly-mid', name: 'Écarté poulie moyenne', category: 'chest', description: 'Milieu des pectoraux' },
  { id: 'push-ups', name: 'Pompes classiques', category: 'chest', description: 'Exercice au poids du corps' },
  { id: 'push-ups-incline', name: 'Pompes inclinées', category: 'chest', description: 'Version facilitée' },
  { id: 'push-ups-decline', name: 'Pompes déclinées', category: 'chest', description: 'Version avancée, pieds surélevés' },
  { id: 'push-ups-wide', name: 'Pompes écartées', category: 'chest', description: 'Accent sur les pectoraux' },
  { id: 'dips-chest', name: 'Dips pectoraux', category: 'chest', description: 'Dips penché en avant' },
  { id: 'machine-chest-press', name: 'Presse pectorale machine', category: 'chest', description: 'Guidé et sécurisé' },
  { id: 'machine-incline-press', name: 'Presse inclinée machine', category: 'chest', description: 'Machine pour le haut' },
  { id: 'pec-deck', name: 'Pec Deck / Butterfly', category: 'chest', description: 'Machine d\'isolation' },
  { id: 'svend-press', name: 'Svend Press', category: 'chest', description: 'Avec plaque, contraction' },
  { id: 'floor-press', name: 'Floor Press', category: 'chest', description: 'Développé au sol' },
  { id: 'landmine-press', name: 'Landmine Press', category: 'chest', description: 'Avec barre en angle' },

  // ==================== DOS ====================
  { id: 'pull-ups', name: 'Tractions pronation', category: 'back', description: 'Exercice de base pour le dos' },
  { id: 'chin-ups', name: 'Tractions supination', category: 'back', description: 'Plus de biceps impliqués' },
  { id: 'neutral-grip-pullup', name: 'Tractions prise neutre', category: 'back', description: 'Prise parallèle' },
  { id: 'lat-pulldown', name: 'Tirage vertical large', category: 'back', description: 'Alternative aux tractions' },
  { id: 'lat-pulldown-close', name: 'Tirage vertical serré', category: 'back', description: 'Prise serrée' },
  { id: 'lat-pulldown-vbar', name: 'Tirage vertical V-Bar', category: 'back', description: 'Avec barre en V' },
  { id: 'straight-arm-pulldown', name: 'Pull-over poulie haute', category: 'back', description: 'Isolation grands dorsaux' },
  { id: 'barbell-row', name: 'Rowing barre pronation', category: 'back', description: 'Épaisseur du dos' },
  { id: 'barbell-row-supinated', name: 'Rowing barre supination', category: 'back', description: 'Plus de biceps' },
  { id: 'pendlay-row', name: 'Pendlay Row', category: 'back', description: 'Rowing explosif' },
  { id: 'dumbbell-row', name: 'Rowing haltère unilatéral', category: 'back', description: 'Un bras à la fois' },
  { id: 'dumbbell-row-two', name: 'Rowing haltères bilatéral', category: 'back', description: 'Deux bras simultanément' },
  { id: 'cable-row', name: 'Tirage horizontal poulie', category: 'back', description: 'Machine câble' },
  { id: 'cable-row-wide', name: 'Tirage horizontal large', category: 'back', description: 'Prise large' },
  { id: 'cable-row-rope', name: 'Tirage horizontal corde', category: 'back', description: 'Avec corde' },
  { id: 't-bar-row', name: 'T-Bar Row', category: 'back', description: 'Rowing avec T-bar' },
  { id: 'chest-supported-row', name: 'Rowing poitrine appuyée', category: 'back', description: 'Isolation stricte' },
  { id: 'machine-row', name: 'Rowing machine', category: 'back', description: 'Guidé et sécurisé' },
  { id: 'deadlift', name: 'Soulevé de terre classique', category: 'back', description: 'Exercice composé roi' },
  { id: 'rack-pull', name: 'Rack Pull', category: 'back', description: 'Soulevé partiel' },
  { id: 'face-pull', name: 'Face Pull', category: 'back', description: 'Arrière d\'épaules et trapèzes' },
  { id: 'reverse-fly-machine', name: 'Oiseau machine', category: 'back', description: 'Arrière d\'épaules' },
  { id: 'hyperextension', name: 'Hyperextensions', category: 'back', description: 'Lombaires et fessiers' },
  { id: 'good-morning', name: 'Good Morning', category: 'back', description: 'Chaîne postérieure' },
  { id: 'meadows-row', name: 'Meadows Row', category: 'back', description: 'Variante landmine' },
  { id: 'seal-row', name: 'Seal Row', category: 'back', description: 'Sur banc surélevé' },
  { id: 'inverted-row', name: 'Rowing inversé', category: 'back', description: 'Au poids du corps' },

  // ==================== ÉPAULES ====================
  { id: 'overhead-press', name: 'Développé militaire barre', category: 'shoulders', description: 'Exercice de base épaules' },
  { id: 'overhead-press-db', name: 'Développé militaire haltères', category: 'shoulders', description: 'Plus de stabilisation' },
  { id: 'seated-press', name: 'Développé assis barre', category: 'shoulders', description: 'Version assise' },
  { id: 'seated-press-db', name: 'Développé assis haltères', category: 'shoulders', description: 'Assis avec haltères' },
  { id: 'push-press', name: 'Push Press', category: 'shoulders', description: 'Avec impulsion des jambes' },
  { id: 'arnold-press', name: 'Arnold Press', category: 'shoulders', description: 'Rotation pendant le mouvement' },
  { id: 'machine-shoulder-press', name: 'Presse épaules machine', category: 'shoulders', description: 'Guidé' },
  { id: 'lateral-raise', name: 'Élévations latérales haltères', category: 'shoulders', description: 'Isolation deltoïde moyen' },
  { id: 'lateral-raise-cable', name: 'Élévations latérales poulie', category: 'shoulders', description: 'Tension constante' },
  { id: 'lateral-raise-machine', name: 'Élévations latérales machine', category: 'shoulders', description: 'Guidé' },
  { id: 'leaning-lateral-raise', name: 'Élévations latérales inclinées', category: 'shoulders', description: 'Penché sur le côté' },
  { id: 'front-raise', name: 'Élévations frontales haltères', category: 'shoulders', description: 'Deltoïde antérieur' },
  { id: 'front-raise-barbell', name: 'Élévations frontales barre', category: 'shoulders', description: 'Avec barre' },
  { id: 'front-raise-cable', name: 'Élévations frontales poulie', category: 'shoulders', description: 'Tension constante' },
  { id: 'front-raise-plate', name: 'Élévations frontales disque', category: 'shoulders', description: 'Avec un disque' },
  { id: 'rear-delt-fly', name: 'Oiseau haltères', category: 'shoulders', description: 'Deltoïde postérieur' },
  { id: 'rear-delt-cable', name: 'Oiseau poulie', category: 'shoulders', description: 'Arrière épaules câble' },
  { id: 'rear-delt-machine', name: 'Oiseau machine', category: 'shoulders', description: 'Pec deck inversé' },
  { id: 'upright-row', name: 'Rowing menton barre', category: 'shoulders', description: 'Épaules et trapèzes' },
  { id: 'upright-row-cable', name: 'Rowing menton poulie', category: 'shoulders', description: 'Version câble' },
  { id: 'shrugs', name: 'Shrugs haltères', category: 'shoulders', description: 'Trapèzes supérieurs' },
  { id: 'shrugs-barbell', name: 'Shrugs barre', category: 'shoulders', description: 'Trapèzes avec barre' },
  { id: 'shrugs-machine', name: 'Shrugs machine', category: 'shoulders', description: 'Trapèzes guidé' },
  { id: 'landmine-lateral', name: 'Élévation latérale landmine', category: 'shoulders', description: 'Avec barre en angle' },
  { id: 'lu-raise', name: 'Lu Raise', category: 'shoulders', description: 'Avant + latéral combiné' },
  { id: 'y-raise', name: 'Y Raise', category: 'shoulders', description: 'Forme de Y' },

  // ==================== BICEPS ====================
  { id: 'barbell-curl', name: 'Curl barre droite', category: 'biceps', description: 'Exercice de base biceps' },
  { id: 'ez-bar-curl', name: 'Curl barre EZ', category: 'biceps', description: 'Moins de stress poignets' },
  { id: 'dumbbell-curl', name: 'Curl haltères alterné', category: 'biceps', description: 'Un bras après l\'autre' },
  { id: 'dumbbell-curl-simul', name: 'Curl haltères simultané', category: 'biceps', description: 'Deux bras ensemble' },
  { id: 'hammer-curl', name: 'Curl marteau', category: 'biceps', description: 'Biceps et brachial' },
  { id: 'hammer-curl-cross', name: 'Curl marteau croisé', category: 'biceps', description: 'Croisé devant le corps' },
  { id: 'preacher-curl', name: 'Curl pupitre barre', category: 'biceps', description: 'Isolation stricte' },
  { id: 'preacher-curl-db', name: 'Curl pupitre haltère', category: 'biceps', description: 'Unilatéral au pupitre' },
  { id: 'preacher-curl-machine', name: 'Curl pupitre machine', category: 'biceps', description: 'Guidé' },
  { id: 'incline-curl', name: 'Curl incliné haltères', category: 'biceps', description: 'Étirement maximal' },
  { id: 'concentration-curl', name: 'Curl concentration', category: 'biceps', description: 'Finition biceps' },
  { id: 'cable-curl', name: 'Curl poulie basse', category: 'biceps', description: 'Tension constante' },
  { id: 'cable-curl-high', name: 'Curl poulie haute', category: 'biceps', description: 'Position bras écartés' },
  { id: 'cable-curl-rope', name: 'Curl poulie corde', category: 'biceps', description: 'Avec corde marteau' },
  { id: 'spider-curl', name: 'Spider Curl', category: 'biceps', description: 'Face au pupitre incliné' },
  { id: 'drag-curl', name: 'Drag Curl', category: 'biceps', description: 'Barre le long du corps' },
  { id: 'reverse-curl', name: 'Curl inversé', category: 'biceps', description: 'Avant-bras et brachial' },
  { id: 'zottman-curl', name: 'Zottman Curl', category: 'biceps', description: 'Rotation pendant le mouvement' },
  { id: 'bayesian-curl', name: 'Bayesian Curl', category: 'biceps', description: 'Curl câble derrière' },
  { id: 'machine-curl', name: 'Curl machine', category: 'biceps', description: 'Guidé' },
  { id: '21s-curl', name: 'Curl 21s', category: 'biceps', description: '7-7-7 répétitions' },

  // ==================== TRICEPS ====================
  { id: 'close-grip-bench', name: 'Développé serré', category: 'triceps', description: 'Exercice composé triceps' },
  { id: 'tricep-pushdown', name: 'Pushdown barre droite', category: 'triceps', description: 'Isolation triceps' },
  { id: 'tricep-pushdown-vbar', name: 'Pushdown V-Bar', category: 'triceps', description: 'Avec barre en V' },
  { id: 'tricep-pushdown-rope', name: 'Pushdown corde', category: 'triceps', description: 'Avec corde' },
  { id: 'tricep-pushdown-reverse', name: 'Pushdown prise inversée', category: 'triceps', description: 'Supination' },
  { id: 'overhead-extension', name: 'Extension verticale haltère', category: 'triceps', description: 'Un haltère à deux mains' },
  { id: 'overhead-extension-db', name: 'Extension verticale unilatérale', category: 'triceps', description: 'Un bras' },
  { id: 'overhead-extension-cable', name: 'Extension verticale poulie', category: 'triceps', description: 'Avec câble' },
  { id: 'overhead-extension-ez', name: 'Extension verticale EZ', category: 'triceps', description: 'Avec barre EZ' },
  { id: 'skull-crusher', name: 'Skull Crusher barre', category: 'triceps', description: 'Extension couché' },
  { id: 'skull-crusher-db', name: 'Skull Crusher haltères', category: 'triceps', description: 'Avec haltères' },
  { id: 'skull-crusher-ez', name: 'Skull Crusher EZ', category: 'triceps', description: 'Avec barre EZ' },
  { id: 'dips-triceps', name: 'Dips triceps', category: 'triceps', description: 'Corps vertical' },
  { id: 'bench-dips', name: 'Dips banc', category: 'triceps', description: 'Mains sur banc' },
  { id: 'kickback', name: 'Kickback haltère', category: 'triceps', description: 'Isolation triceps' },
  { id: 'kickback-cable', name: 'Kickback poulie', category: 'triceps', description: 'Tension constante' },
  { id: 'diamond-pushups', name: 'Pompes diamant', category: 'triceps', description: 'Mains rapprochées' },
  { id: 'jm-press', name: 'JM Press', category: 'triceps', description: 'Hybride skull/press' },
  { id: 'tate-press', name: 'Tate Press', category: 'triceps', description: 'Coudes écartés' },
  { id: 'machine-tricep', name: 'Extension triceps machine', category: 'triceps', description: 'Guidé' },

  // ==================== JAMBES ====================
  { id: 'squat', name: 'Squat barre haute', category: 'legs', description: 'Exercice roi des jambes' },
  { id: 'squat-low-bar', name: 'Squat barre basse', category: 'legs', description: 'Plus de hanche' },
  { id: 'front-squat', name: 'Front Squat', category: 'legs', description: 'Accent quadriceps' },
  { id: 'goblet-squat', name: 'Goblet Squat', category: 'legs', description: 'Avec haltère ou kettlebell' },
  { id: 'hack-squat', name: 'Hack Squat machine', category: 'legs', description: 'Machine guidée' },
  { id: 'smith-squat', name: 'Squat Smith machine', category: 'legs', description: 'Barre guidée' },
  { id: 'leg-press', name: 'Presse à cuisses', category: 'legs', description: 'Machine de base' },
  { id: 'leg-press-high', name: 'Presse pieds hauts', category: 'legs', description: 'Accent fessiers/ischios' },
  { id: 'leg-press-narrow', name: 'Presse pieds serrés', category: 'legs', description: 'Accent quadriceps' },
  { id: 'leg-extension', name: 'Leg Extension', category: 'legs', description: 'Isolation quadriceps' },
  { id: 'leg-curl-lying', name: 'Leg Curl couché', category: 'legs', description: 'Ischio-jambiers couché' },
  { id: 'leg-curl-seated', name: 'Leg Curl assis', category: 'legs', description: 'Ischio-jambiers assis' },
  { id: 'leg-curl-standing', name: 'Leg Curl debout', category: 'legs', description: 'Ischio-jambiers debout' },
  { id: 'lunges', name: 'Fentes avant', category: 'legs', description: 'Exercice unilatéral' },
  { id: 'lunges-walking', name: 'Fentes marchées', category: 'legs', description: 'En avançant' },
  { id: 'lunges-reverse', name: 'Fentes arrière', category: 'legs', description: 'Pas en arrière' },
  { id: 'lunges-lateral', name: 'Fentes latérales', category: 'legs', description: 'Sur le côté' },
  { id: 'romanian-deadlift', name: 'Soulevé de terre roumain barre', category: 'legs', description: 'Ischio-jambiers' },
  { id: 'romanian-deadlift-db', name: 'Soulevé roumain haltères', category: 'legs', description: 'Avec haltères' },
  { id: 'stiff-leg-deadlift', name: 'Soulevé jambes tendues', category: 'legs', description: 'Jambes quasi-tendues' },
  { id: 'single-leg-rdl', name: 'Soulevé roumain unipodal', category: 'legs', description: 'Sur une jambe' },
  { id: 'nordic-curl', name: 'Nordic Curl', category: 'legs', description: 'Ischio avancé' },
  { id: 'sissy-squat', name: 'Sissy Squat', category: 'legs', description: 'Isolation quadriceps extrême' },
  { id: 'calf-raise-standing', name: 'Mollets debout machine', category: 'legs', description: 'Gastrocnémiens' },
  { id: 'calf-raise-db', name: 'Mollets debout haltères', category: 'legs', description: 'Avec haltères' },
  { id: 'calf-raise-smith', name: 'Mollets Smith machine', category: 'legs', description: 'Sur Smith' },
  { id: 'seated-calf', name: 'Mollets assis machine', category: 'legs', description: 'Soléaire' },
  { id: 'donkey-calf', name: 'Mollets âne', category: 'legs', description: 'Position penchée' },
  { id: 'leg-press-calf', name: 'Mollets presse', category: 'legs', description: 'Sur presse à cuisses' },
  { id: 'adductor-machine', name: 'Adducteurs machine', category: 'legs', description: 'Intérieur des cuisses' },
  { id: 'abductor-machine', name: 'Abducteurs machine', category: 'legs', description: 'Extérieur des cuisses' },
  { id: 'belt-squat', name: 'Belt Squat', category: 'legs', description: 'Squat avec ceinture' },
  { id: 'pendulum-squat', name: 'Pendulum Squat', category: 'legs', description: 'Machine pendulaire' },

  // ==================== FESSIERS ====================
  { id: 'hip-thrust', name: 'Hip Thrust barre', category: 'glutes', description: 'Exercice principal fessiers' },
  { id: 'hip-thrust-db', name: 'Hip Thrust haltère', category: 'glutes', description: 'Avec haltère' },
  { id: 'hip-thrust-machine', name: 'Hip Thrust machine', category: 'glutes', description: 'Machine dédiée' },
  { id: 'hip-thrust-single', name: 'Hip Thrust unilatéral', category: 'glutes', description: 'Une jambe' },
  { id: 'glute-bridge', name: 'Pont fessier', category: 'glutes', description: 'Version au sol' },
  { id: 'glute-bridge-single', name: 'Pont fessier unilatéral', category: 'glutes', description: 'Une jambe' },
  { id: 'cable-kickback', name: 'Kickback poulie', category: 'glutes', description: 'Extension hanche câble' },
  { id: 'cable-pull-through', name: 'Pull Through', category: 'glutes', description: 'Extension hanche poulie' },
  { id: 'sumo-deadlift', name: 'Soulevé sumo', category: 'glutes', description: 'Fessiers et adducteurs' },
  { id: 'step-ups', name: 'Step-ups haltères', category: 'glutes', description: 'Montée sur banc' },
  { id: 'step-ups-lateral', name: 'Step-ups latéraux', category: 'glutes', description: 'Montée latérale' },
  { id: 'bulgarian-split', name: 'Bulgarian Split Squat', category: 'glutes', description: 'Squat bulgare' },
  { id: 'curtsy-lunge', name: 'Fente révérence', category: 'glutes', description: 'Croisée derrière' },
  { id: 'glute-kickback-machine', name: 'Kickback machine', category: 'glutes', description: 'Machine fessiers' },
  { id: 'donkey-kick', name: 'Donkey Kick', category: 'glutes', description: 'À quatre pattes' },
  { id: 'fire-hydrant', name: 'Fire Hydrant', category: 'glutes', description: 'Abduction à quatre pattes' },
  { id: 'frog-pump', name: 'Frog Pump', category: 'glutes', description: 'Pieds joints, genoux écartés' },
  { id: 'clamshell', name: 'Clamshell', category: 'glutes', description: 'Ouverture latérale' },
  { id: 'banded-walks', name: 'Marche avec bande', category: 'glutes', description: 'Latéral avec élastique' },
  { id: 'reverse-hyper', name: 'Reverse Hyper', category: 'glutes', description: 'Extension inverse' },
  { id: 'kneeling-squat', name: 'Squat à genoux', category: 'glutes', description: 'À genoux avec barre' },

  // ==================== ABDOMINAUX ====================
  { id: 'crunch', name: 'Crunch classique', category: 'abs', description: 'Exercice de base abdos' },
  { id: 'crunch-machine', name: 'Crunch machine', category: 'abs', description: 'Avec résistance' },
  { id: 'cable-crunch', name: 'Crunch poulie', category: 'abs', description: 'Avec câble' },
  { id: 'decline-crunch', name: 'Crunch décliné', category: 'abs', description: 'Sur banc décliné' },
  { id: 'reverse-crunch', name: 'Crunch inversé', category: 'abs', description: 'Lever les hanches' },
  { id: 'bicycle-crunch', name: 'Crunch bicyclette', category: 'abs', description: 'Mouvement pédalage' },
  { id: 'plank', name: 'Planche frontale', category: 'abs', description: 'Gainage frontal' },
  { id: 'plank-weighted', name: 'Planche lestée', category: 'abs', description: 'Avec poids sur le dos' },
  { id: 'side-plank', name: 'Planche latérale', category: 'abs', description: 'Gainage obliques' },
  { id: 'plank-to-pushup', name: 'Planche vers pompe', category: 'abs', description: 'Transition dynamique' },
  { id: 'leg-raise', name: 'Relevé de jambes couché', category: 'abs', description: 'Abdos inférieurs' },
  { id: 'hanging-leg-raise', name: 'Relevé de jambes suspendu', category: 'abs', description: 'À la barre' },
  { id: 'hanging-knee-raise', name: 'Relevé de genoux suspendu', category: 'abs', description: 'Version facilitée' },
  { id: 'captain-chair', name: 'Chaise romaine', category: 'abs', description: 'Relevé de jambes appuyé' },
  { id: 'russian-twist', name: 'Russian Twist', category: 'abs', description: 'Rotation obliques' },
  { id: 'russian-twist-weighted', name: 'Russian Twist lesté', category: 'abs', description: 'Avec poids' },
  { id: 'woodchop', name: 'Woodchop poulie', category: 'abs', description: 'Rotation diagonale' },
  { id: 'woodchop-low-high', name: 'Woodchop bas vers haut', category: 'abs', description: 'De bas en haut' },
  { id: 'pallof-press', name: 'Pallof Press', category: 'abs', description: 'Anti-rotation' },
  { id: 'ab-wheel', name: 'Roue abdominale', category: 'abs', description: 'Exercice avancé' },
  { id: 'dead-bug', name: 'Dead Bug', category: 'abs', description: 'Stabilisation' },
  { id: 'bird-dog', name: 'Bird Dog', category: 'abs', description: 'Coordination' },
  { id: 'hollow-body-hold', name: 'Hollow Body Hold', category: 'abs', description: 'Position creuse' },
  { id: 'l-sit', name: 'L-Sit', category: 'abs', description: 'Position en L' },
  { id: 'dragon-flag', name: 'Dragon Flag', category: 'abs', description: 'Exercice très avancé' },
  { id: 'toes-to-bar', name: 'Toes to Bar', category: 'abs', description: 'Pieds à la barre' },
  { id: 'v-up', name: 'V-Up', category: 'abs', description: 'Toucher les pieds' },
  { id: 'flutter-kicks', name: 'Flutter Kicks', category: 'abs', description: 'Battements de jambes' },
  { id: 'mountain-climbers', name: 'Mountain Climbers', category: 'abs', description: 'Grimpeur' },
  { id: 'situp', name: 'Sit-up classique', category: 'abs', description: 'Redressement complet' },

  // ==================== CARDIO ====================
  { id: 'treadmill-run', name: 'Course tapis', category: 'cardio', description: 'Course sur tapis' },
  { id: 'treadmill-walk', name: 'Marche tapis', category: 'cardio', description: 'Marche rapide' },
  { id: 'treadmill-incline', name: 'Marche inclinée', category: 'cardio', description: 'Tapis incliné' },
  { id: 'bike-stationary', name: 'Vélo stationnaire', category: 'cardio', description: 'Vélo d\'appartement' },
  { id: 'bike-spinning', name: 'Spinning', category: 'cardio', description: 'Cours de vélo intense' },
  { id: 'bike-assault', name: 'Assault Bike', category: 'cardio', description: 'Vélo à air' },
  { id: 'elliptical', name: 'Elliptique', category: 'cardio', description: 'Faible impact' },
  { id: 'stair-climber', name: 'Stepper escalier', category: 'cardio', description: 'Simulation escalier' },
  { id: 'stair-master', name: 'StairMaster', category: 'cardio', description: 'Escalier roulant' },
  { id: 'rowing-machine', name: 'Rameur', category: 'cardio', description: 'Cardio complet' },
  { id: 'ski-erg', name: 'Ski Erg', category: 'cardio', description: 'Simulation ski' },
  { id: 'jump-rope', name: 'Corde à sauter', category: 'cardio', description: 'Simple et efficace' },
  { id: 'jump-rope-double', name: 'Double unders', category: 'cardio', description: 'Deux tours par saut' },
  { id: 'burpees', name: 'Burpees', category: 'cardio', description: 'Exercice complet' },
  { id: 'box-jump', name: 'Box Jump', category: 'cardio', description: 'Saut sur box' },
  { id: 'box-step-up', name: 'Step-up cardio', category: 'cardio', description: 'Montée rapide' },
  { id: 'jumping-jacks', name: 'Jumping Jacks', category: 'cardio', description: 'Sauts écartés' },
  { id: 'high-knees', name: 'High Knees', category: 'cardio', description: 'Genoux hauts' },
  { id: 'butt-kicks', name: 'Butt Kicks', category: 'cardio', description: 'Talons fesses' },
  { id: 'battle-ropes', name: 'Battle Ropes', category: 'cardio', description: 'Cordes ondulatoires' },
  { id: 'kettlebell-swing', name: 'Kettlebell Swing', category: 'cardio', description: 'Balancier kettlebell' },
  { id: 'sled-push', name: 'Poussée de traîneau', category: 'cardio', description: 'Prowler push' },
  { id: 'sled-pull', name: 'Tirage de traîneau', category: 'cardio', description: 'Prowler pull' },
  { id: 'farmers-walk', name: 'Farmer Walk', category: 'cardio', description: 'Marche avec charges' },
  { id: 'swimming', name: 'Natation', category: 'cardio', description: 'Cardio aquatique' },
  { id: 'shadow-boxing', name: 'Shadow Boxing', category: 'cardio', description: 'Boxe dans le vide' },
  { id: 'hiit-circuit', name: 'Circuit HIIT', category: 'cardio', description: 'Intervalles haute intensité' },
  { id: 'tabata', name: 'Tabata', category: 'cardio', description: '20s effort / 10s repos' },
  { id: 'sprints', name: 'Sprints', category: 'cardio', description: 'Course rapide' },
];

export function getExercisesByCategory(category: MuscleCategory): Exercise[] {
  return exercises.filter((exercise) => exercise.category === category);
}

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((exercise) => exercise.id === id);
}

export function getAllCategories(): MuscleCategory[] {
  return [...new Set(exercises.map((e) => e.category))];
}

export function searchExercises(query: string): Exercise[] {
  const lowerQuery = query.toLowerCase();
  return exercises.filter(
    (e) =>
      e.name.toLowerCase().includes(lowerQuery) ||
      e.description?.toLowerCase().includes(lowerQuery)
  );
}
